version: '3'
services:
  tech-memo:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
        SSH_PUBLIC_KEY: ${SSH_PUBLIC_KEY}
    container_name: tech-memo
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    user: node
